version: '3'

services:
  redis:
    image: redisfab/redisearch:2.8-arm64v8-bionic
    volumes:
      - ./.docker/redis/data:/data:rw
    ports:
      - "6382:6379"

###> doctrine/doctrine-bundle ###
  database:
    ports:
      - "${POSTGRES_PORT:-}:5432"
###< doctrine/doctrine-bundle ###
