version: '3'

services:
  redis:
    ports:
      - "${REDIS_PORT:-}:6379"

###> doctrine/doctrine-bundle ###
  database:
    ports:
      - "${POSTGRES_PORT:-}:5432"
###< doctrine/doctrine-bundle ###
